version: '3.9'
services:
  # web:
  #   build: .
  #   ports: 
  #     - 3000:3000
  #   depends_on:
  #     - mysql
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   ports:
  #     - 8080:80
  #   links:
  #     - mysql:db
  # mysql:
  #   restart: always
  #   image: mysql:latest
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - "MYSQL_ROOT_PASSWORD=654321"
  #     - "MYSQL_DATABASE=mysql"
  #     - "TZ=Asia/Shanghai"
  # mongo:
  #   image: mongo:latest
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #     MONGO_INITDB_DATABASE: project
  #   ports:
  #     - 27017:27017
  # mongo-express:
  #   image: mongo-express:latest
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - mongo
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #     - ME_CONFIG_MONGODB_PORT=27017
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
  #     - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
  #     - ME_CONFIG_MONGODB_AUTH_USERNAME=root
  #     - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
  #     - ME_CONFIG_BASICAUTH_USERNAME=root
  #     - ME_CONFIG_BASICAUTH_PASSWORD=root
  # redis:
  #   image: redis:latest
  #   command: redis-server --requirepass 123456
  #   ports:
  #     - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0-alpha1-arm64
    ports:
      - 9200:9200

